"""
admin/coin_routes.py – Coin-based (offline) payment support.

Coin transactions are machine-initiated: the ESP32 detects coin insertion
and calls POST /coin/transaction to record payment and trigger dispense.

Collection: coin_transactions
{
  machine_id, session_id, items, amount,
  status: "completed" | "failed",
  created_at, completed_at
}
"""
from datetime import datetime
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from typing import Optional

from app.database import get_collection
from app.services.machine_service import deduct_stock
from app.utils.logger import logger

router = APIRouter(prefix="/coin", tags=["Coin Payments"])


class CoinTransactionRequest(BaseModel):
    machine_id: str
    session_id: str           # Unique session generated by ESP32
    items: list               # [{"product_id": ..., "quantity": ..., "product_name": ...}]
    amount_inserted: float    # Coins inserted (INR equivalent)
    total_price: float        # Expected total


class CoinTransactionResponse(BaseModel):
    transaction_id: str
    status: str
    message: str
    change_due: float


@router.post(
    "/transaction",
    response_model=CoinTransactionResponse,
    summary="[ESP32] Record coin payment and trigger dispense",
)
async def coin_transaction(request: CoinTransactionRequest):
    """
    Called by the ESP32 when coins are inserted and accepted.
    - Validates enough coins were inserted
    - Records the transaction
    - Deducts stock
    """
    if request.amount_inserted < request.total_price:
        raise HTTPException(
            status_code=400,
            detail=f"Insufficient coins. Inserted: ₹{request.amount_inserted}, Required: ₹{request.total_price}",
        )

    change_due = round(request.amount_inserted - request.total_price, 2)
    now = datetime.utcnow()

    # Dedup check: same session_id already processed?
    col = get_collection("coin_transactions")
    existing = await col.find_one({"session_id": request.session_id})
    if existing:
        return CoinTransactionResponse(
            transaction_id=str(existing["_id"]),
            status="completed",
            message="Already processed.",
            change_due=change_due,
        )

    doc = {
        "machine_id": request.machine_id,
        "session_id": request.session_id,
        "items": request.items,
        "amount": request.total_price,
        "amount_inserted": request.amount_inserted,
        "change_due": change_due,
        "status": "processing",
        "payment_method": "COIN",
        "created_at": now,
        "completed_at": None,
    }
    result = await col.insert_one(doc)
    tx_id = str(result.inserted_id)

    # Deduct stock
    try:
        await deduct_stock(request.machine_id, [
            {"product_id": i["product_id"], "quantity": i["quantity"]}
            for i in request.items
        ])
        # Also create an order record so admin analytics picks it up
        orders_col = get_collection("orders")
        await orders_col.insert_one({
            "user_id": f"coin:{request.session_id}",
            "machine_id": request.machine_id,
            "machine_name": "",  # Will be enriched by ESP32 if needed
            "items": [
                {
                    "product_id": i["product_id"],
                    "product_name": i.get("product_name", ""),
                    "pad_type": i.get("pad_type", ""),
                    "price": i.get("price", 0),
                    "quantity": i["quantity"],
                }
                for i in request.items
            ],
            "total_amount": request.total_price,
            "status": "COMPLETED",
            "payment_method": "COIN",
            "razorpay_order_id": None,
            "razorpay_payment_id": None,
            "razorpay_signature": None,
            "dispense_attempts": 1,
            "dispense_error": None,
            "created_at": now,
            "updated_at": now,
            "completed_at": now,
        })

        await col.update_one(
            {"_id": result.inserted_id},
            {"$set": {"status": "completed", "completed_at": now}},
        )
        logger.info(f"[Coin] Transaction {tx_id} completed for machine {request.machine_id}")
        return CoinTransactionResponse(
            transaction_id=tx_id,
            status="completed",
            message="Dispense authorised.",
            change_due=change_due,
        )

    except Exception as exc:
        await col.update_one(
            {"_id": result.inserted_id},
            {"$set": {"status": "failed", "error": str(exc)}},
        )
        logger.error(f"[Coin] Transaction {tx_id} failed: {exc}")
        raise HTTPException(status_code=500, detail="Coin transaction failed.")
